from __future__ import annotations

import logging
from pathlib import Path
from uuid import uuid4

from app.application.models.optimization_request import (
    OptimizationRequest,
)
from app.application.services.resume_optimization_service import (
    ResumeOptimizationService,
)
from app.database.models.guest import Guest
from app.database.models.guest_resume import GuestResume
from app.database.models.referral import Referral
from app.guest.services.guest_usage_service import (
    GuestUsageService,
)
from app.referral.services.referral_service import (
    ReferralService,
)


logger = logging.getLogger(__name__)


class GuestOptimizationService:
    """
    Coordinates guest resume optimization.

    Guest-specific rules live here.

    The actual resume optimization is delegated to the
    existing ResumeOptimizationService.

    Responsibilities:

        1. Validate guest resume ownership.
        2. Validate guest session.
        3. Validate guest usage.
        4. Validate the source DOCX.
        5. Execute resume optimization.
        6. Verify optimization success.
        7. Verify the generated output artifact.
        8. Consume one guest optimization sample.
        9. Complete an eligible referral.
       10. Grant the referrer's reward.
    """

    def __init__(self, db) -> None:
        self.db = db

        self.usage_service = GuestUsageService(db)

        self.referral_service = ReferralService(db)

        self.optimization_service = (
            ResumeOptimizationService()
        )

    # ==========================================================
    # Optimization
    # ==========================================================

    def optimize(
    self,
    guest: Guest,
    guest_resume: GuestResume,
    guest_session_id: str,
    job_description: str,
    role_id: str,
    selected_skills: list[str],
):
        """
        Optimize a guest resume.

        Usage is consumed only after successful optimization.

        A referral is completed only after the referred guest
        successfully completes an optimization.
        """

        # ------------------------------------------------------
        # 1. Validate resume ownership
        # ------------------------------------------------------

        self._validate_resume_ownership(
            guest=guest,
            guest_resume=guest_resume,
        )

        # ------------------------------------------------------
        # 2. Validate guest session
        # ------------------------------------------------------

        self.usage_service._get_valid_session(
            guest=guest,
            guest_session_id=guest_session_id,
        )

        # ------------------------------------------------------
        # 3. Check guest usage
        # ------------------------------------------------------

        if not self.usage_service.can_optimize(
            guest,
        ):
            raise ValueError(
                "Guest optimization limit reached."
            )

        # ------------------------------------------------------
        # 4. Validate source resume
        # ------------------------------------------------------

        resume_path = Path(
            guest_resume.file_path,
        )

        if not resume_path.exists():
            raise FileNotFoundError(
                "Guest resume file is no longer available."
            )

        if not resume_path.is_file():
            raise FileNotFoundError(
                "Guest resume file is invalid."
            )

        # ------------------------------------------------------
        # 5. Create requested output path
        # ------------------------------------------------------

        requested_output_path = self._build_output_path(
            resume_path,
        )

        # ------------------------------------------------------
        # 6. Build optimization request
        # ------------------------------------------------------

        request = OptimizationRequest(
    resume_path=str(resume_path),
    job_description=job_description,
    output_path=str(requested_output_path),
    role_id=role_id,
    selected_skills=selected_skills,
)

        # Track the artifact actually generated by the
        # optimization engine.
        generated_output_path: Path | None = None

        try:
            # --------------------------------------------------
            # 7. Execute existing optimization engine
            # --------------------------------------------------

            result = (
                self.optimization_service.optimize(
                    request,
                )
            )

            # --------------------------------------------------
            # 8. Verify optimization result
            # --------------------------------------------------

            if not result.success:
                raise ValueError(
                    result.message,
                )

            # --------------------------------------------------
            # 9. Validate returned output path
            #
            # The optimization service is authoritative about
            # the artifact it actually generated.
            # --------------------------------------------------

            if not result.output_path:
                raise FileNotFoundError(
                    "Optimization completed but no "
                    "output path was returned."
                )

            generated_output_path = Path(
                result.output_path,
            )

            # --------------------------------------------------
            # 10. Verify generated output exists
            # --------------------------------------------------

            if not generated_output_path.exists():
                raise FileNotFoundError(
                    "Optimization completed but the "
                    "optimized resume was not generated."
                )

            if not generated_output_path.is_file():
                raise FileNotFoundError(
                    "Optimization output is invalid."
                )

            # --------------------------------------------------
            # 11. Consume guest usage
            # --------------------------------------------------

            self.usage_service.consume_optimization(
                guest=guest,
                guest_session_id=guest_session_id,
            )

            # --------------------------------------------------
            # 12. Complete eligible referral
            # --------------------------------------------------

            self._complete_referral_if_eligible(
                referred_guest=guest,
            )

            # --------------------------------------------------
            # 13. Success
            # --------------------------------------------------

            logger.info(
                "Guest resume optimization completed: "
                "guest_id=%s guest_resume_id=%s "
                "output_path=%s",
                guest.id,
                guest_resume.id,
                generated_output_path,
            )

            return result

        except Exception:
            logger.exception(
                "Guest resume optimization failed: "
                "guest_id=%s guest_resume_id=%s",
                guest.id,
                guest_resume.id,
            )

            # --------------------------------------------------
            # Remove generated output if optimization failed.
            #
            # IMPORTANT:
            # Delete the artifact returned by the optimizer,
            # not merely the requested path.
            # --------------------------------------------------

            if (
                generated_output_path is not None
                and generated_output_path.exists()
            ):
                try:
                    generated_output_path.unlink()

                except OSError:
                    logger.exception(
                        "Failed to remove partial optimization "
                        "output: %s",
                        generated_output_path,
                    )

            raise

    # ==========================================================
    # Validation
    # ==========================================================

    @staticmethod
    def _validate_resume_ownership(
        guest: Guest,
        guest_resume: GuestResume,
    ) -> None:
        """
        Ensure the resume belongs to the supplied guest.
        """

        if guest_resume.guest_id != guest.id:
            raise ValueError(
                "Guest resume does not belong to this guest."
            )

    # ==========================================================
    # Output
    # ==========================================================

    @staticmethod
    def _build_output_path(
        resume_path: Path,
    ) -> Path:
        """
        Build a unique output filename.

        This prevents repeated optimizations from overwriting
        an earlier generated DOCX.
        """

        unique_id = uuid4().hex[:12]

        return (
            resume_path.parent
            / (
                f"{resume_path.stem}"
                f"_optimized_{unique_id}"
                f".docx"
            )
        )

    # ==========================================================
    # Referral
    # ==========================================================

    def _complete_referral_if_eligible(
        self,
        referred_guest: Guest,
    ) -> None:
        """
        Complete and reward the referral belonging to the
        supplied guest.

        Only a pending, unrewarded referral is eligible.

        If the guest was not referred, nothing happens.

        If the referral was already completed or rewarded,
        nothing happens.
        """

        referral = (
            self.db.query(Referral)
            .filter(
                Referral.referred_guest_id
                == referred_guest.id,
                Referral.status == "pending",
                Referral.reward_granted.is_(False),
            )
            .first()
        )

        if referral is None:
            return

        # ------------------------------------------------------
        # Complete referral
        # ------------------------------------------------------

        self.referral_service.complete_referral(
            referral,
        )

        # ------------------------------------------------------
        # Grant referrer's reward
        # ------------------------------------------------------

        self.referral_service.grant_reward(
            referral,
        )

        logger.info(
            "Referral completed and reward granted: "
            "referral_id=%s "
            "referred_guest_id=%s "
            "referrer_guest_id=%s",
            referral.id,
            referral.referred_guest_id,
            referral.referrer_guest_id,
        )