from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(slots=True)
class PromotionDecision:
    """
    One planned promotion.
    """

    technology: str

    section: str

    priority: int

    reason: str

    confidence: float


@dataclass(slots=True)
class PromotionPlan:
    """
    Promotion decisions generated by
    the Intelligence Engine.
    """

    decisions: list[
        PromotionDecision
    ] = field(
        default_factory=list,
    )
