"""
app.planner.blueprint.optimization_blueprint
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Final output of the Planner.

Every planner engine contributes to this blueprint.
The Optimizer consumes only this object.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.knowledge.builder.optimization_knowledge import (
    OptimizationKnowledge,
)
from app.planner.budget.optimization_budget import (
    OptimizationBudget,
)
from app.planner.decision.optimization_decision import (
    OptimizationDecision,
)
from app.planner.evidence.evidence_report import (
    EvidenceReport,
)
from app.planner.goal.optimization_goal import (
    OptimizationGoal,
)
from app.planner.priority.priority_plan import (
    PriorityPlan,
)
from app.planner.prompt.prompt_plan import (
    PromptPlan,
)
from app.planner.rewrite.rewrite_plan import (
    RewritePlan,
)
from app.planner.section.section_plan import (
    SectionPlan,
)


@dataclass(slots=True)
class OptimizationBlueprint:
    """
    Complete optimization strategy generated by the Planner.

    The Optimizer consumes this object as the final
    planning contract.
    """

    # -------------------------------------------------
    # Knowledge
    # -------------------------------------------------

    knowledge: OptimizationKnowledge | None = None

    # -------------------------------------------------
    # Core Planning
    # -------------------------------------------------

    goal: OptimizationGoal | None = None

    decision: OptimizationDecision | None = None

    priorities: PriorityPlan = field(
        default_factory=PriorityPlan
    )

    evidence: EvidenceReport = field(
        default_factory=EvidenceReport
    )

    section_plan: SectionPlan = field(
        default_factory=SectionPlan
    )

    rewrite_plan: RewritePlan = field(
        default_factory=RewritePlan
    )

    # -------------------------------------------------
    # Budget
    # -------------------------------------------------

    budget: OptimizationBudget | None = None

    # -------------------------------------------------
    # Prompt Planning
    # -------------------------------------------------

    prompt_plan: PromptPlan = field(
        default_factory=PromptPlan
    )

    # -------------------------------------------------
    # Execution Metadata
    # -------------------------------------------------

    target_sections: list[str] = field(
        default_factory=list
    )

    rewrite_strategy: str = ""

    prompt_count: int = 0

    token_budget: int = 0

    safety_rules: list[str] = field(
        default_factory=list
    )

    execution_order: list[str] = field(
        default_factory=list
    )

    metadata: dict[str, str] = field(
        default_factory=dict
    )