"""
ResumeOptimizer exception hierarchy.
"""

from .ai import (
    AIAuthenticationError,
    AIConfigurationError,
    AIConnectionError,
    AIError,
    AIGenerationError,
    AIInitializationError,
    AIModelError,
    AIRequestError,
    AIResponseError,
    AIRateLimitError,
    AITimeoutError,
    AITokenLimitError,
)
from .analysis import (
    AnalysisError,
    ATSAnalysisError,
    ClassificationError,
    DocumentAnalysisError,
    EducationAnalysisError,
    ExperienceAnalysisError,
    ExtractionError,
    JobDescriptionAnalysisError,
    ParsingError,
    ResumeAnalysisError,
    SkillAnalysisError,
)
from .auth import (
    AccountDisabledError,
    AuthenticationConfigurationError,
    AuthenticationError,
    AuthorizationError,
    ExpiredTokenError,
    InvalidCredentialsError,
    InvalidTokenError,
    PermissionDeniedError,
    TokenGenerationError,
    TokenVerificationError,
)
from .base import (
    ConfigurationError,
    DependencyError,
    DomainError,
    InitializationError,
    ResourceNotFoundError,
    ResumeOptimizerError,
    ValidationError,
)
from .database import (
    ConstraintViolationError,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseInitializationError,
    DatabaseMigrationError,
    DuplicateEntityError,
    EntityNotFoundError,
    RepositoryError,
    TransactionError,
)
from .knowledge import (
    KnowledgeBuildError,
    KnowledgeCacheError,
    KnowledgeConfigurationError,
    KnowledgeError,
    KnowledgeIndexError,
    KnowledgeInitializationError,
    KnowledgeLoadingError,
    KnowledgeSearchError,
    KnowledgeSourceError,
    KnowledgeValidationError,
    KnowledgeVersionError,
)
from .optimization import (
    ContentReplacementError,
    LayoutPreservationError,
    OptimizationError,
    OptimizationExecutionError,
    OptimizationLimitExceededError,
    OptimizationStrategyError,
    PlannerError,
    PromptGenerationError,
    SkillMatchingError,
    ValidationFailureError,
    WriterError,
)
from .storage import (
    FileAlreadyExistsError,
    FileDeleteError,
    FileDownloadError,
    FileReadError,
    FileSizeLimitExceededError,
    FileUploadError,
    FileWriteError,
    InvalidFileFormatError,
    InvalidFileTypeError,
    StorageConfigurationError,
    StorageConnectionError,
    StorageError,
    StorageInitializationError,
)

__all__ = [
    # Base
    "ResumeOptimizerError",
    "DomainError",
    "ValidationError",
    "ConfigurationError",
    "ResourceNotFoundError",
    "DependencyError",
    "InitializationError",

    # Database
    "DatabaseError",
    "DatabaseConnectionError",
    "DatabaseInitializationError",
    "DatabaseMigrationError",
    "TransactionError",
    "RepositoryError",
    "EntityNotFoundError",
    "DuplicateEntityError",
    "ConstraintViolationError",

    # Storage
    "StorageError",
    "StorageConnectionError",
    "StorageConfigurationError",
    "StorageInitializationError",
    "FileAlreadyExistsError",
    "FileReadError",
    "FileWriteError",
    "FileDeleteError",
    "FileUploadError",
    "FileDownloadError",
    "InvalidFileTypeError",
    "InvalidFileFormatError",
    "FileSizeLimitExceededError",

    # Knowledge
    "KnowledgeError",
    "KnowledgeInitializationError",
    "KnowledgeConfigurationError",
    "KnowledgeSourceError",
    "KnowledgeLoadingError",
    "KnowledgeBuildError",
    "KnowledgeValidationError",
    "KnowledgeIndexError",
    "KnowledgeSearchError",
    "KnowledgeCacheError",
    "KnowledgeVersionError",

    # Analysis
    "AnalysisError",
    "DocumentAnalysisError",
    "ResumeAnalysisError",
    "JobDescriptionAnalysisError",
    "ParsingError",
    "ExtractionError",
    "ClassificationError",
    "SkillAnalysisError",
    "ExperienceAnalysisError",
    "EducationAnalysisError",
    "ATSAnalysisError",

    # AI
    "AIError",
    "AIConfigurationError",
    "AIInitializationError",
    "AIConnectionError",
    "AIAuthenticationError",
    "AIRateLimitError",
    "AIRequestError",
    "AIResponseError",
    "AIModelError",
    "AITimeoutError",
    "AITokenLimitError",
    "AIGenerationError",

    # Auth
    "AuthenticationError",
    "AuthorizationError",
    "InvalidCredentialsError",
    "InvalidTokenError",
    "ExpiredTokenError",
    "TokenGenerationError",
    "TokenVerificationError",
    "PermissionDeniedError",
    "AccountDisabledError",
    "AuthenticationConfigurationError",

    # Optimization
    "OptimizationError",
    "PlannerError",
    "SkillMatchingError",
    "OptimizationStrategyError",
    "PromptGenerationError",
    "OptimizationExecutionError",
    "ValidationFailureError",
    "WriterError",
    "LayoutPreservationError",
    "ContentReplacementError",
    "OptimizationLimitExceededError",
]