from __future__ import annotations

from app.engine.models.document import Document
from app.engine.planner.plan import OptimizationPlan

from app.engine.optimizer.text_optimizer import (
    TextOptimizer,
)

from app.engine.optimizer.experience_optimizer import (
    ExperienceOptimizer,
)

from app.engine.optimizer.skill_optimizer import (
    SkillOptimizer,
)

from app.engine.optimizer.section_optimizer import (
    SectionOptimizer,
)


class OptimizationCoordinator:
    """
    ResumeOptimizer V3

    Executes the OptimizationPlan.

    Responsibilities
    ----------------
    - Never create decisions
    - Never analyze the document
    - Never call AI
    - Never validate output

    It ONLY executes the plan generated by the Planner.
    """

    def optimize(
        self,
        document: Document,
        plan: OptimizationPlan,
    ) -> Document:

        optimized = document

        # -----------------------------------------
        # Execute optimization stages
        # -----------------------------------------

        optimized = self._optimize_sections(
            optimized,
            plan,
        )

        optimized = self._optimize_experience(
            optimized,
            plan,
        )

        optimized = self._optimize_skills(
            optimized,
            plan,
        )

        optimized = self._optimize_text(
            optimized,
            plan,
        )

        return optimized

    def _optimize_sections(
        self,
        document: Document,
        plan: OptimizationPlan,
    ) -> Document:

        return document

    def _optimize_experience(
        self,
        document: Document,
        plan: OptimizationPlan,
    ) -> Document:

        return document

    def _optimize_skills(
        self,
        document: Document,
        plan: OptimizationPlan,
    ) -> Document:

        return document

    def _optimize_text(
        self,
        document: Document,
        plan: OptimizationPlan,
    ) -> Document:

        return document