from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(slots=True)
class PromotionDecision:
    """
    One technology promotion decision.

    Generated by the Intelligence Engine.

    It describes:
        - WHAT should be promoted
        - WHERE it should be promoted
        - WHY it should be promoted
    """


    # --------------------------------------------------
    # Technology
    # --------------------------------------------------

    technology: str

    # --------------------------------------------------
    # Placement
    # --------------------------------------------------

    section: str


    # --------------------------------------------------
    # Decision
    # --------------------------------------------------

    priority: int

    reason: str


    # --------------------------------------------------
    # Optional intelligence metadata
    # --------------------------------------------------

    knowledge_id: str | None = None

    category: str | None = None

    confidence: float = 0.0


    # --------------------------------------------------
    # Helpers
    # --------------------------------------------------

    def is_high_priority(
        self,
        threshold: int = 1,
    ) -> bool:

        return self.priority <= threshold



@dataclass(slots=True)
class PromotionPlan:
    """
    Collection of promotion decisions generated
    by the Intelligence Engine.

    Consumed by:

        Intelligence
             ↓
        Planner
             ↓
        Optimizer
    """


    decisions: list[PromotionDecision] = field(
        default_factory=list,
    )


    # --------------------------------------------------
    # Helpers
    # --------------------------------------------------

    def add(
        self,
        decision: PromotionDecision,
    ) -> None:

        self.decisions.append(
            decision
        )


    def high_priority(
        self,
    ) -> list[PromotionDecision]:

        return [
            decision
            for decision in self.decisions
            if decision.is_high_priority()
        ]