from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True)
class RewritePlan:
    """
    One controlled rewrite instruction.

    Generated by Planner.

    Responsibilities:
        - Identify what needs improvement
        - Define where the change happens
        - Explain why the change is needed

    Does NOT:
        - Rewrite text
        - Modify DOCX
        - Call AI

    Consumed by:
        Planner
            ↓
        Optimizer
            ↓
        Writer
    """

    # --------------------------------------------------
    # Target Location
    # --------------------------------------------------

    paragraph_id: str

    section: str

    # --------------------------------------------------
    # Optimization Target
    # --------------------------------------------------

    technology: str | None = None

    action: str = "improve"

    # --------------------------------------------------
    # Priority
    # --------------------------------------------------

    priority: int = 0

    # --------------------------------------------------
    # Explanation
    # --------------------------------------------------

    reason: str = ""

    confidence: float = 0.0

    # --------------------------------------------------
    # Context Preservation
    # --------------------------------------------------

    original_text: str | None = None

    target_keywords: list[str] | None = None

    # --------------------------------------------------
    # Validation
    # --------------------------------------------------

    preserve_formatting: bool = True

    allow_length_change: bool = False