from __future__ import annotations

from dataclasses import dataclass

from app.engine.models.layout_budget import (
    LayoutBudget,
)


@dataclass(slots=True, frozen=True)
class LayoutConstraints:
    """
    Hard layout constraints generated by the Planner.

    These constraints are enforced by the Optimizer
    and verified by the Validator.
    """

    max_characters: int

    max_words: int

    max_lines: int

    allow_overflow: bool

    tolerance_percentage: float


class LayoutBudgetPlanner:
    """
    Converts LayoutBudget into optimization
    constraints.

    Planner never estimates layout.

    Planner only decides the limits that
    Optimizer must obey.
    """

    @staticmethod
    def build(
    budget: LayoutBudget,
) -> LayoutConstraints:

        return LayoutConstraints(

        # Temporary: triple every limit
        max_characters=budget.max_characters * 3,

        max_words=budget.max_words * 3,

        max_lines=max(1, budget.max_lines * 3),

        # Allow overflow during testing
        allow_overflow=True,

        # Allow up to 200% tolerance
        tolerance_percentage=200.0,

    )