from __future__ import annotations

from dataclasses import dataclass

from app.engine.models.layout_budget import LayoutBudget


@dataclass(slots=True, frozen=True)
class LayoutConstraints:
    """
    Hard layout constraints generated by the Planner.

    These constraints are enforced by the Optimizer
    and verified by the Validator.
    """

    max_characters: int

    max_words: int

    max_lines: int

    allow_overflow: bool

    tolerance_percentage: float


class LayoutBudgetPlanner:
    """
    Converts LayoutBudget into optimization
    constraints.

    Planner never estimates layout.

    Planner only decides the limits that
    Optimizer must obey.
    """

    @staticmethod
    def build(
        budget: LayoutBudget,
    ) -> LayoutConstraints:

        return LayoutConstraints(

            max_characters=budget.max_characters,

            max_words=budget.max_words,

            max_lines=budget.max_lines,

            allow_overflow=budget.allow_overflow,

            tolerance_percentage=budget.tolerance_percentage,

        )