from enum import Enum


class ParagraphType(str, Enum):

    NAME = "NAME"

    JOB_TITLE = "JOB_TITLE"

    CONTACT = "CONTACT"

    HEADING = "HEADING"

    SUMMARY = "SUMMARY"

    COMPANY = "COMPANY"

    EXPERIENCE = "EXPERIENCE"

    PROJECT_TITLE = "PROJECT_TITLE"

    PROJECT_TECHNOLOGY = "PROJECT_TECHNOLOGY"

    PROJECT_DESCRIPTION = "PROJECT_DESCRIPTION"

    SKILLS = "SKILLS"

    EDUCATION = "EDUCATION"

    EMPTY = "EMPTY"

    UNKNOWN = "UNKNOWN"