import uuid
from datetime import datetime

from sqlalchemy import DateTime
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship

from app.database.base import Base


class GeneratedResume(Base):
    """
    Optimized resume generated by an OptimizationJob.
    """

    __tablename__ = "generated_resumes"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )

    optimization_job_id: Mapped[str] = mapped_column(
        ForeignKey("optimization_jobs.id"),
        unique=True,
        nullable=False,
        index=True,
    )

    filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    file_path: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
    )

    file_size: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    optimization_job: Mapped["OptimizationJob"] = relationship(
        "OptimizationJob",
        back_populates="generated_resume",
    )

    downloads: Mapped[list["Download"]] = relationship(
        "Download",
        back_populates="resume_output",
        cascade="all, delete-orphan",
    )