from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class JobContext:
    """
    Structured target job information.

    Represents the job description understanding
    generated by Analyzer / Intelligence layers.

    Responsibilities:

        - Carry target role information.
        - Carry required skills.
        - Carry job expectations.
        - Provide AI optimization direction.


    Does NOT:

        - Parse raw JD.
        - Call AI.
        - Rewrite resume.
    """


    # --------------------------------------------------
    # Target role
    # --------------------------------------------------

    role_title: str | None = None

    role_family: str | None = None

    seniority: str | None = None


    # --------------------------------------------------
    # Required skills
    # --------------------------------------------------

    required_skills: list[str] = field(
        default_factory=list,
    )


    preferred_skills: list[str] = field(
        default_factory=list,
    )


    skill_categories: dict[str, list[str]] = field(
        default_factory=dict,
    )


    # --------------------------------------------------
    # Job expectations
    # --------------------------------------------------

    responsibilities: list[str] = field(
        default_factory=list,
    )


    technical_expectations: list[str] = field(
        default_factory=list,
    )


    soft_skill_expectations: list[str] = field(
        default_factory=list,
    )


    # --------------------------------------------------
    # Constraints from JD
    # --------------------------------------------------

    experience_requirement: str | None = None

    education_requirement: str | None = None


    # --------------------------------------------------
    # Raw information backup
    # --------------------------------------------------

    raw_description: str | None = None


    metadata: dict[str, Any] = field(
        default_factory=dict,
    )


    # --------------------------------------------------
    # Helpers
    # --------------------------------------------------

    def all_required_skills(
        self,
    ) -> list[str]:
        """
        Return unique required skill set.
        """

        return list(
            dict.fromkeys(
                self.required_skills
                +
                self.preferred_skills
            )
        )



    def has_skill(
        self,
        skill: str,
    ) -> bool:
        """
        Check whether JD requires skill.
        """

        skill = skill.lower().strip()

        return any(
            item.lower().strip() == skill
            for item in self.all_required_skills()
        )



    def add_metadata(
        self,
        key: str,
        value: Any,
    ) -> None:
        """
        Store future JD intelligence data.
        """

        self.metadata[key] = value